Add DISABLE_RESPONDENT_ENROLMENT case event category
ONSdigital/rm-casesvc-api pull request #13
Opened 2018-04-12 16:26 UTC by andrewmil

Added DISABLE_RESPONDENT_ENROLMENT case event category

Works with other PR's:
[response-operations-ui](https://github.com/ONSdigital/response-operations-ui/pull/123)
[rm-backstage](https://github.com/ONSdigital/ras-backstage/pull/96)
[ras-party](https://github.com/ONSdigital/ras-party/pull/122)
[rm-case](https://github.com/ONSdigital/rm-case-service/pull/28)

[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/248545529/US022+Disable+respondent+enrolment+to+a+survey)
[Trello](https://trello.com/c/1ez85L0y/51-us022-int-disable-respondents-enrolment-to-a-survey-l)

2018-04-13 08:19 UTC, gemmai95 approved these changes

2018-04-13 12:00 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [US022: INT Disable respondents enrolment to a survey [L]](https://trello.com/c/1ez85L0y/51-us022-int-disable-respondents-enrolment-to-a-survey-l)

2018-04-16 14:29 UTC, tej99 requested changes

2018-04-16 14:29 UTC, tej99 commented on src/main/java/uk/gov/ons/ctp/response/casesvc/representation/CaseDTO.java
> +    ACCOUNT_CREATED, ACTIVATED, DEACTIVATED, DISABLED, DISABLE_RESPONDENT_ENROLMENT,
Should there be a new event? I feel like the event is still DISABLED just a new category

2018-04-17 09:44 UTC, jwgwalton approved these changes
Squash.

2018-04-17 10:53 UTC, tej99 approved these changes

2018-04-17 10:54 UTC, merged