Remove bi/update sampleunitnotification message format
ONSdigital/rm-casesvc-api pull request #24
Opened 2018-07-19 11:16 UTC by gemmai95

# Motivation and Context

Required to allow B cases to always be created for collection exercises.

# What has changed

Change to sample unit notification to remove child.

# How to test?

Run with branch in case and collection exercise service and check B cases are being created when collection exercise is executed.

# Links

[Trello] https://trello.com/c/ZWg5l0Kt

2018-07-20 07:58 UTC, ajmaddaford requested changes

2018-07-20 07:58 UTC, ajmaddaford commented on src/main/resources/casesvc/xsd/inbound/SampleUnitNotification.xsd
> +            <xs:element name="sampleUnitChild" type="SampleUnitBase"
Now that `SampleUnitBase` is being used as a concrete type (rather than extended), I think it would be clearer if it was renamed `SampleUnit`

2018-07-23 09:56 UTC, andrewmil approved these changes
Looks good :+1:
Unit/Acceptance tests passing with the case/collection exercise PR's

2018-07-23 19:43 UTC, ajmaddaford approved these changes

2018-07-24 07:46 UTC, merged