Adding metadata to caseevents dto
ONSdigital/rm-casesvc-api pull request #33
Opened 2018-11-20 13:31 UTC by ryangrundy7

# Motivation and Context
In response-operation-ui, we want to be able to see the respondent name on the responses status page when a external user has completed a collection exercise. For this to happen, a new field needs to be added to the case events dto to be able to store any metadata that can be given to the case service.

# What has changed
- Added metadata to case events table

# How to test?
- Run `mvn clean install` and it should build successfully
- Run with the [case branch](https://github.com/ONSdigital/rm-case-service/tree/adding-metadata-to-caseevents), [R-ops branch](https://github.com/ONSdigital/response-operations-ui/tree/us211-display-respondent-for-seft-rus-ce-in-response-status), [Frontstage branch](https://github.com/ONSdigital/ras-frontstage/tree/us211-display-respondent-for-seft-rus-ce-in-response-status) and complete a SEFT collection exercise. When completed, look on response ops response status page and the completed collex should have a respondent name attached to it.
- Run with acceptance tests

# Links
[Trello](https://trello.com/c/1rcfmtok)

2018-11-20 13:34 UTC, mfcrocker approved these changes

2018-11-28 13:21 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ctp/response/casesvc/representation/CaseEventCreationRequestDTO.java
> +  private HashMap<String, String> metadata;
You should use the interface `Map` instead of the concrete implementation `HashMap`.

2018-11-28 13:21 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ctp/response/casesvc/representation/CaseEventDTO.java
> +  private HashMap<String, String> metadata;
You should use the interface Map instead of the concrete implementation HashMap

2018-11-28 13:21 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ctp/response/casesvc/representation/CreatedCaseEventDTO.java
> +  private HashMap<String, String> metadata;
You should use the interface Map instead of the concrete implementation HashMap

2018-11-28 13:22 UTC, NickGrantX requested changes
In Java, we use the _interface_ rather than the _concrete_ class (i.e. List instead of ArrayList, Map instead of HashMap, Set instead of HashSet etc. etc.)

2018-12-05 13:44 UTC, NickGrantX approved these changes
LGTM 👍

2018-12-06 09:24 UTC, merged